### ISSUE TITLE
Still being updated?

### ISSUE THREAD

**Issue by skylord123** [opendns/merchant-esolutions-php#3]
Is this still being maintained?

I recommend updating the Guzzle version. This bundle was preventing me from upgrading but luckily there was: https://github.com/bburim/merchant-esolutions-php

**Comment by tabacco** [comment]
We're not really maintaining this ourselves anymore, but I'm happy to review and merge pull requests and tag new builds as changes come in.

(Also, sorry for the delayed response, I was on vacation)
